#!/bin/bash
# This script runs the JSONLDPlayground code.
# Before running this script for the first time 
# you may need to run:
#     chmod +x jsonldplayground
#
# run ./jsonldplayground for the usage

if [ ! -d "tools/target/appassembler/bin" ]; then
    mvn -quiet clean install -DskipTests
fi

chmod u+x tools/target/appassembler/bin/*
tools/target/appassembler/bin/jsonldplayground "$@"
