#!/bin/bash
# This script runs the RDF2JSONLD code, which converts an input file or URI in rdfxml/n3 to JSON-LD.
# The following commands are required to be run before this can be used (left out of the script itself
# because they can take a while to run):
#     chmod +x rdf2jsonld
#     chmod +x tools/target/appassembler/bin/*
# 	  mvn -quiet install
# run ./rdf2jsonld for the usage

tools/target/appassembler/bin/rdf2jsonld
